version: '3.8'


services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackend
    container_name: vortex_backend
    restart: always
    env_file:
      - .env
    command: python3 /app/backend/main.py prod
    expose:
      - "8080"
    networks:
      proj_network:
        ipv4_address: 172.15.1.4
#    network_mode: host

#  certbot:
#    image: certbot/certbot
#    container_name: vortex_certbot
#    env_file:
#      - .env
#    volumes:
#      - certbot_www:/var/www/certbot/:rw
#      - certbot_conf:/etc/letsencrypt/:rw
#    # remove flag "--staging" to make real SSL (not for tests)
#    command: certonly --staging --webroot --webroot-path=/var/www/certbot/ --agree-tos --email ${CERTBOT_EMAIL} -d domain.ru -d www.domain.ru
#    networks:
#      proj_network:
#        ipv4_address: 172.15.1.3
#    depends_on:
#      - nginx

  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    container_name: vortex_nginx_front
    restart: always
#    volumes:
#      - certbot_www:/var/www/certbot/:ro
#      - certbot_conf:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      proj_network:
        ipv4_address: 172.15.1.2
    depends_on:
      - backend


networks:
  proj_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.1.0/24


#volumes:
#  certbot_www:
#  certbot_conf:
