openapi: 3.0.0


info:
  title: Vortex
  description: FastAPI backend for Vortex
  version: 1.0.0


servers:
  - description: Production server
    url: http://i.p.v.4/api
  - description: Development server
    url: http://127.0.0.1:8000/api


paths:
  /send_mail:
    post:
      summary: Sending e-mail with data from POST-form
      operationId: send_mail__post
      requestBody:
        description: POST-form data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Иван"
                phone:
                  type: string
                  example: "89054764513"
                service:
                  type: string
                  example: "Какая-то услуга"
                message:
                  type: string
                  example: "Какое-то длинное сообщение от юзера"
              required:
                - name
                - phone
                - service
                - message
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '500':
          description: Send mail error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'


components:
  schemas:
    Status:
      title: Status
      type: object
      properties:
        status:
          title: Status message ("ok" or "error")
          type: string
